name: orbs
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - backports.zstd=1.3.0=py314h680f03e_0
  - blas=1.0=mkl
  - boto3=1.42.29=pyhd8ed1ab_0
  - botocore=1.42.30=pyhd8ed1ab_0
  - bottleneck=1.4.2=py314h6a40391_1
  - brotli-python=1.2.0=py314h3de4e8d_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py314hdb19cb5_0
  - cycler=0.12.1=py314h06a4308_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.3=h7354ed3_4
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py314hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - graphite2=1.3.14=h295c915_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.5.2=py314h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - kiwisolver=1.4.9=py314h24d9097_0
  - kneed=0.8.5=pyhd8ed1ab_1
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.3.0=h3539ee5_0
  - libcups=2.4.15=hbe4054b_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.4=h77a78f3_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libmpdec=4.0.0=h5eee18b_0
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvmlite=0.46.0=py314h946fb2a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.7=py314h06a4308_0
  - matplotlib-base=3.10.7=py314h54cb298_0
  - mesalib=25.1.5=h31e3550_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py314hacdc0fc_0
  - mkl_fft=2.1.1=py314h2be417e_0
  - mkl_random=1.3.0=py314hda4e5d8_0
  - mysql-common=9.3.0=h9e076cb_4
  - mysql-libs=9.3.0=h6ecde68_4
  - narwhals=2.7.0=py314h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - numba=0.63.1=py314h8169c2f_0
  - numexpr=2.14.1=py314hc3af6af_0
  - numpy=2.3.5=py314hc4ca38b_0
  - numpy-base=2.3.5=py314h7c74580_0
  - openldap=2.6.10=he9288cc_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=py314h06a4308_1
  - pandas=2.3.3=py314hda4e5d8_1
  - pcre2=10.46=hf426167_0
  - pillow=12.0.0=py314h3b88751_1
  - pip=25.3=pyh0d26453_0
  - pixman=0.46.4=h7934f7d_0
  - plotly=6.5.0=pyhd8ed1ab_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.2.5=py314h06a4308_0
  - pyqt=6.9.1=py314h43fb04a_0
  - pyqt6-sip=13.10.2=py314hee96239_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.14.2=h90eec9f_101_cp314
  - python-dateutil=2.9.0post0=py314h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.14=2_cp314
  - pytz=2025.2=py314h06a4308_0
  - qtbase=6.9.2=hd13baf8_5
  - qtdeclarative=6.9.2=h55666de_1
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_1
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - readline=8.3=hc2a1206_0
  - s3transfer=0.16.0=pyhd8ed1ab_0
  - scikit-learn=1.8.0=py314h973aee8_0
  - scipy=1.16.3=py314h3d0cd3c_0
  - setuptools=80.9.0=py314h06a4308_0
  - sgp4=2.25=py314h9891dd4_2
  - sip=6.12.0=py314h695c4d2_0
  - six=1.17.0=py314h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - threadpoolctl=3.5.0=py314h6fa48dc_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py314h5eee18b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - umap-learn=0.5.11=py314hdafbbf9_0
  - wayland=1.24.0=hdac8c69_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - attrs==25.4.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - dbcv==0.1.1
      - frozenlist==1.8.0
      - idna==3.11
      - mpmath==1.3.0
      - multidict==6.7.0
      - nodejs-wheel-binaries==24.12.0
      - propcache==0.4.1
      - python-vlc==3.0.21203
      - pytubefix==10.3.6
      - requests==2.32.5
      - s-dbw==0.4.0
      - urllib3==2.6.2
      - viasckde==1.0.1
      - wisdom-tree==0.2.0
      - yarl==1.22.0
prefix: /home/san/miniconda3/envs/orbs
