name: orbs
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - defaults
dependencies:
  - matplotlib
  - scikit-learn
  - pandas
  - sgp4
  - plotly
  - tqdm
  - kneed
  - umap-learn
  - boto3
prefix: /home/san/miniconda3/envs/orbs
